# generate_doe.py
#
# Generates the Abaqus *PARAMETER include files for the full-factorial
# design of experiments.
#
# Run:
#   python3 generate_doe.py            # write doe_params/eta_params_runNN.inp
#   python3 generate_doe.py --check    # verify existing files match, write nothing
#
# The four dimensionless disease scaling parameters are each varied between
# a baseline level (B, eta = 0) and a moderate-disease level
# (M, eta = 0.5 * eta_max).  Run order follows the manuscript convention, (Fig. 6).

from __future__ import print_function

import argparse
import itertools
import os
import sys


# ----------------------------------------------------------------------
# Factor definitions
# ----------------------------------------------------------------------

# Severe-disease reference values eta_max (Table 4).  The moderate DOE
# level is half of each, and the baseline level is zero.
ETA_MAX = (
    ('eta_D', 0.92),
    ('eta_a', 0.50),
    ('eta_T', 0.50),
    ('eta_mu', 3.31),
)

MODERATE_FRACTION = 0.5

# gamma_h is Model 1's hypertrophy growth rate (m1.inp PROPS(4), the
# "GAMMA_G" that drives theta_h).  Unlike the four eta factors above it is
# not a fraction of a severity maximum -- its two DOE levels are the
# manuscript's rate values directly: ungrown (0.0) and the growth rate
# that reaches theta_h ~ 2 after one time unit (0.69).
GAMMA_H_LEVELS = {'B': 0.0, 'M': 0.69}

# Factor name width used when writing the *PARAMETER block, chosen so the
# equals signs line up as in the original hand-checked files.
NAME_WIDTH = 6

PARAMS_DIR = 'doe_params'
FILE_PATTERN = 'eta_params_run%02d.inp'


def factor_levels():
    """Return an ordered list of (name, {level: value}) for each factor."""
    levels = []
    for name, eta_max in ETA_MAX:
        levels.append((name, {
            'B': 0.0,
            'M': MODERATE_FRACTION * eta_max,
        }))
    levels.append(('gamma_h', dict(GAMMA_H_LEVELS)))
    return levels


def factor_names():
    """Return the ordered factor names, including gamma_h."""
    return [name for name, _ in factor_levels()]


def doe_table():
    """Return the full-factorial run table.

    Each entry is a list of (name, level_label, value) for one run.  The
    Cartesian product is taken with the last factor varying slowest:
    eta_D fastest, ..., eta_mu, then gamma_h slowest.  Runs 1-16 are
    exactly the original 2^4 DOE at gamma_h=B; runs 17-32 repeat them at
    gamma_h=M.
    """
    levels = factor_levels()
    names = [name for name, _ in levels]

    runs = []
    # itertools.product varies its last argument fastest, so the factor
    # list is reversed on the way in and each row reversed on the way out.
    for combination in itertools.product(*[['B', 'M'] for _ in levels][::-1]):
        combination = combination[::-1]
        run = []
        for index, level_label in enumerate(combination):
            name = names[index]
            value = levels[index][1][level_label]
            run.append((name, level_label, value))
        runs.append(run)

    return runs


# ----------------------------------------------------------------------
# Include-file rendering
# ----------------------------------------------------------------------

def render_include(run_number, total_runs, run):
    """Return the text of one eta_params_runNN.inp include file."""
    level_summary = ', '.join(
        '%s=%s' % (name, level_label) for name, level_label, _ in run
    )

    lines = []
    lines.append('**' + '=' * 70)
    lines.append('** DOE run %02d of %d' % (run_number, total_runs))
    lines.append('** Levels: %s' % level_summary)
    lines.append('**   B = baseline (eta = 0), '
                 'M = moderate (eta = 0.5 * eta_ref)')
    lines.append('** Auto-generated by generate_doe.py -- '
                 'do not edit by hand.')
    lines.append('**' + '=' * 70)
    lines.append('*PARAMETER')
    for name, _, value in run:
        lines.append('%s = %s' % (name.ljust(NAME_WIDTH), repr(value)))
    lines.append('**')

    return '\n'.join(lines) + '\n'


def include_path(params_dir, run_number):
    return os.path.join(params_dir, FILE_PATTERN % run_number)


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Generate the Abaqus *PARAMETER include files for the '
                    'full-factorial DOE.'
    )
    parser.add_argument(
        '--dir', default=PARAMS_DIR,
        help='Output directory for the include files'
    )
    parser.add_argument(
        '--check', action='store_true',
        help='Compare against the existing files instead of writing'
    )
    args = parser.parse_args()

    runs = doe_table()
    total_runs = len(runs)

    if not args.check and not os.path.isdir(args.dir):
        os.makedirs(args.dir)

    mismatches = []

    for index, run in enumerate(runs):
        run_number = index + 1
        path = include_path(args.dir, run_number)
        text = render_include(run_number, total_runs, run)

        if args.check:
            if not os.path.exists(path):
                mismatches.append('%s is missing' % path)
                continue
            with open(path, 'r') as existing_file:
                existing_text = existing_file.read()
            if existing_text != text:
                mismatches.append('%s differs from the generated content'
                                  % path)
        else:
            with open(path, 'w') as output_file:
                output_file.write(text)

    if args.check:
        if mismatches:
            print('DOE include files do NOT match generate_doe.py:')
            for message in mismatches:
                print('  %s' % message)
            return 1
        print('All %d DOE include files in %s match generate_doe.py exactly.'
              % (total_runs, args.dir))
        return 0

    print('Wrote %d DOE include files to %s/' % (total_runs, args.dir))
    return 0


if __name__ == '__main__':
    sys.exit(main())
